testing-library/user-event

__tests__/click.js
src/index.js

BREAKING CHANGE: 🧨  clicking disabled radio button no longer fires events

fix: 🐛 don't fire events when clicking disabled radio button

---

package-lock.json
package.json

Switch @testing-library/dom to be a peerDep + devDep

---

__tests__/vue/dblclick.js
__tests__/vue/selectoptions.js
__tests__/vue/type.js
package-lock.json
package.json

Hi! 👋 this is a PR to add additional tests for Vue.
~I can't seem to find the way to make the `preventDefault` test pass ([link](https://github.com/testing-library/user-event/compare/add-vue-tests?expand=1#diff-c15ea404ef18eb0acc40c894ece19235R47-R48)). Any help would be greatly appreciated!~
Apart from that, I've only noticed small differences from React tests:
* `focus` event isn't being emitted twice on selectoptions ([link](https://github.com/testing-library/user-event/compare/add-vue-tests?expand=1#diff-4e8bbadf93b5bc4474efd2532de7c58eR55)).
* input/change events ([link](https://github.com/testing-library/user-event/compare/add-vue-tests?expand=1#diff-c15ea404ef18eb0acc40c894ece19235R77-R80)).
I guess @calebeby might want to take a look at this, too :)

test: 💍 add Vue tests for type, dblclick, selectoptions

---

__tests__/react/selectoptions.js
src/index.js

BREAKING CHANGE: 🧨 selectOptions is now firing a change event
Rebase of #131

fix: fire onChange event on select element change

---

README.md

Was reading the README and noticed that this example destructures `getByText` but uses `getByTestId`.
Wasn't able to find a `CONTRIBUTORS` file so I'm not sure if you're accepting PRs but I hope this is helpful! Happy to make any changes to commit format etc.
And finally a huge thanks to this project and all of the `@testing-library` ecosystem!

Fix example in README for `type` method

---

README.md
__tests__/react/tab.js
src/index.js

This feature allows you to easily test tabbing in focus traps. 
example:
```userEvent.tab({focusTrap: containerElement})```
also adds tab to readme and converts expects to use jest dom for tabs

feat: focus trap on tab

---

README.md

fix: updated the documentation for the `type` method

---

__tests__/react/tab.js
src/index.js

prior to node 11, Array.sort was unstable for arrays w/ length > 10.
https://twitter.com/mathias/status/1036626116654637057
for this reason, the tab() function needs to account for this in it's sorting.
for example under node 10 in this test:
> 'abcdefghijklmnopqrstuvwxyz'.split('').sort(() => 0).join('')
will give you 'nacdefghijklmbopqrstuvwxyz'

fix: account for sorting bug in node 10

---

__tests__/react/click.js
src/index.js

I came across this issue while testing form components. It is common for a form to focus inputs that are invalid, and I was seeing strange behavior where I couldn't invalidate and focus the same input element twice. I did a bit of digging and see that events call blur after the click event is fired, so I believe we can fix this by checking to see if focus has already changed before calling blur.

fix(click): click no longer blurs when focus changes during onClick event

---

__tests__/react/tab.js
src/index.js

this PR fixes a false positive that allowed the `tab` function to focus disabled elements, which is not the browser behavior
done @ [![Open Source Saturday](https://img.shields.io/badge/%E2%9D%A4%EF%B8%8F-open%20source%20saturday-F64060.svg)](https://www.meetup.com/it-IT/Open-Source-Saturday-Milano/) Milano

fix tab focus on disabled elements false positive

---

__tests__/react/click.js
src/index.js

Because `userEvent.click` should simulate real browsers' behavior, we need to take into account the result of each event.
In this particular case if `mouseDown` event has `preventDefault`, it should stop focus event.
Here is the source code of Google Chrome Blink for reference (others follow the same convention):
https://chromium.googlesource.com/chromium/blink/+/master/Source/core/input/EventHandler.cpp#972
```
bool swallowEvent = !dispatchMouseEvent(EventTypeNames::mousedown, mev.innerNode(), m_clickCount, mouseEvent);
```
`dispatchMouseEvent` return value means "continue default handling", so `swallowEvent` is `true` in case of `preventDefault` usage.
Just below there is call for focus event which is triggered only if `swallowEvent === false` 
```
swallowEvent = swallowEvent || …
```

Correct focus changes based on mouseDown result

---

__tests__/react/type.js
__tests__/vue/type.js
src/index.js

This is related to #161 .
I took the liberty to implement it. I look forward to your comments or suggestions.

Handle maxLength for userEvent.type

---

.all-contributorsrc
README.md
__tests__/react/click.js
__tests__/react/dblclick.js
src/index.js

Blur events

---

__tests__/react/type.js
src/index.js

When using .type() with an input field that had already text inside the
new text is added to the field
BREAKING CHANGE: 🧨 Using .type() with an input field that had text already inside preserve
the exisiting value and appends the typed text

fix: 🐛 type supports fields with previous text

---

__tests__/react/tab.js
src/index.js

Hi @Gpx and @kentcdodds. 👋 
I ran into an issue where `tab()` blows up if the case under test has not rendered any elements which are focusable. Probably a bit of a corner case, but it would be nice to have it covered.
Hope the change is okay. This is my first open-source contribution! 😅

fix(tab): Keep focus on the document if there are no enabled, focusable elements

---

typings/index.d.ts

I found there is no userEvent.clear type definition in version 10.1.0 (https://github.com/testing-library/user-event/pull/233)
I just added userEvcent.clear

fix: Add TypeScript userEvent.clear definition

---

src/index.js

I'm using user-event in the browser, not sure if it's officially supported but it mostly works. 
There's a problem with `type`, it's removing the last char from the text because the browser returns -1 from `element.maxLength`. I changed it to only slice with maxLength when it's a positive number.

fix: type when element.maxLength is -1

---

README.md
src/index.js

We pass the `init` argument through so that the underlying
click event can be created with ctrlKey set to true if desired.

src: Add support for ctrl click.

---

__tests__/react/click.js
__tests__/react/dblclick.js
src/index.js

Hi I have solved the issue for ticket #225 
The issue was present also for double click
Regards
Marco

[click/dblClick] Prevent blur when clicking the same element

---

.travis.yml

There exists a 12MB binary in the tarball published to npm called `cc-test-reporter`.
This looks like a happy accident to me. It's only neccessary on the CI machine and should be removed before publishing the library.
The npm tarball for `user-event` is 12.9MB ; of which 12.8MB is this `cc-test-reporter` binary.

Reduce size of npm package by 99%

---

README.md

**Problem:** had initially missed this method in the documentation when it was added because it wasn't formatted the same as the others.
**Solution:** format `clear` consistent with other methods.

docs: fix README formatting

---

typings/index.d.ts

We've added the ability to pass the init argument. We need to document that in the typescript definition

Document type for `click()`

---

README.md
__tests__/react/clear.js
__tests__/react/upload.js
src/index.js
typings/index.d.ts

Closes #267
I tried to implement it as close as possible to real user interaction.
There is [no `cypress` implementation](https://github.com/testing-library/user-event/pull/279) for uploading files at this moment to check.
At first I thought about emulating `input.files` with `DataTransfer` to get `FileList` but Node needs a polyfill. I haven't found reliable implementation of `DataTransfer`. I mocked `FileList` API on my own therefore.
Looking forward for reviews and suggestions. Thanks.

feat(upload): Add upload API

---

__tests__/react/type.js
__tests__/vue/type.js
src/index.js

Fixes #281 
When `type()` behavior was changed to append text, rather than replace it, `maxLength` handling was not updated to take any pre-existing text into account.  As a result, when using multiple `.type()` calls, the user is able to enter text in excess of `maxLength`.   More details in #281

Fix maxLength handling over multiple type() calls

---

__tests__/react/upload.js
src/index.js

I was looking at `FileList` implementation and noted that `item` function must return `File` or `null` instead `undefined`. Here is [`jsdom` implementation](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/file-api/FileList-impl.js#L10) of it. Also fix wrong expectation in test that's not cause an error when it must. Also I removed unnecessary expectations in `upload` tests.

fix(upload): FileList item function must return null instead undefined when it can't find a file

---

src/__tests__/clear.js
src/index.js

Resolves issue #268
Per the issue comments, I believed that the change would only require calling `fireEvent.change` in the `clear` method; but that turned out not to be the case.
React deduplicates events that it fires so that it doesn't emit multiple `onChange` events with the same value. Using `element.value = ""` causes React to expect a change event to have been fired, so calling `fireEvent.change` has will be considered a duplicate event and no event will be fired. I added tests to verify the expected behavior (they fail before the second commit, as one would expect).
The solution I landed on, and I'm super open to feedback, was to follow the logic I found in [stackoverflow](https://stackoverflow.com/questions/23892547/what-is-the-best-way-to-trigger-onchange-event-in-react-js). I …

Make `clear` method fire `onChange` handlers

---

src/__tests__/click.js
src/__tests__/dblclick.js
src/index.js
typings/index.d.ts

**What**:
This ensures that all mouse events are fired with the correct values for the [button](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button), [buttons](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons), and [detail](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/detail) properties. This emulates what a browser would do, and is important for code that relies on this behavior. In addition, it should be possible to pass custom properties through to all events (e.g. `altKey`, and screen positions).
**Why**:
Tests should simulate how a browser fires them as closely as possible.
**How**:
Looked at the spec for each property and emulated the required behavior. Also tested in a real application that relies on some of them.
By default, `click` …

Fire mouse events with the correct properties

---

README.md
src/__tests__/selectoptions.js
src/index.js
typings/index.d.ts

**What**:
Allow selection of combobox options by html nodes. e.g.
```js
render(
<select>
<option value="1">first option</option>
</select>,
)
userEvent.selectOptions(screen.getByRole('combobox'), screen.getByText('first option'))
```
**Why**:
Since users don't directly interact with option values, this should allow for testing in a more user-like way.
**How**:
In addition to checking for the `option.value` string, now it also checks if the node itself is in the given array.
**Checklist**:
---
**Comments**:
Ideally, I think `userEvent.selectOptions` should receive option text instead of option values, and warn if it can't find the given option.text.
Since that would be a breaking change, I think this PR could be a good first step towards that direction.
**Related to**:
* …

feat: allow selecting options by nodes

---

package-lock.json
package.json
src/__tests__/type.js
src/__tests__/wrapping-in-act-is-unnecessary.js
src/index.js

**What**: wrap `type` in the asyncWrapper from DOM Testing Library
**Why**:
This fixes issues with act warnings when using `type` with React Testing Library (I expect the same would be necessary for angular change detection).
**How**: Upgrade to the latest version of DOM Testing Library (it is now required) so we can get the `getConfig` export to use the `asyncWrapper`.
**Checklist**:
BREAKING CHANGE: The DOM Testing Library version 7.9.0 or greater is required

fix(type): wrap type in the asyncWrapper from DOM Testing Library

---

README.md
package-lock.json
package.json
src/__tests__/click.js
src/__tests__/helpers/utils.js
src/__tests__/selectoptions.js
src/__tests__/type-modifiers.js
src/__tests__/type.js
src/index.js
src/tick.js
src/type.js
tests/setup-env.js

**What**: feat(type): support special characters (like `{enter}`)
**Why**:
Closes #306
Closes #301
Closes #235
Closes #181
Closes #172
Closes #31
**How**:
Oh boy... Totally reworked the `type` functionality. Also made some pretty cool utilities for the tests which might be useful elsewhere.
**Checklist**:

feat(type): support special charaters (like {enter})

---

package.json
src/__tests__/helpers/utils.js
src/__tests__/toggleselectoptions.js
src/__tests__/type-modifiers.js
src/__tests__/type.js
src/type.js

**What**: fix(type): handle selectionRange properly
**Why**: Closes #309
**How**: create a new `calculateNewBackspaceValue` out of the `calculateNewValue` function because there's no reasonable way to abstract that. I promise.
**Checklist**:

fix(type): handle selectionRange properly

---

src/__tests__/helpers/customElement.js
src/__tests__/helpers/utils.js
src/__tests__/type.js
src/type.js

**What**: fixes #319
**Why**: in order to support custom elements
**How**: modify the `currentElement` helper to return nested `activeElement` inside shadow DOM
**Checklist**:
There were more changes required in the testing helpers than in the actual library - I'm open to suggestions on how to improve my suggested solution :)

Support customElements

---

src/__tests__/type-modifiers.js
src/__tests__/type.js
src/type.js
typings/index.d.ts

**What**: fix(type): ensure the selectionStart/End are consistent with browsers 
**Why**:
Closes: #321
Closes: #318
Closes: #316
**How**:
Investigated how the browser deals with situations where values are changed programmatically: https://jsbin.com/decutel/3/edit?html,js,output
The rule is: If the value changes to something that it would not have naturally from the user's input, then send the selection range to the end.
Because we're programmatically changing it, the browser automatically sends the selection range to the end, so we have to correct for that by moving the selection range back to where it would be (if the value doesn't change from what we expected after we fire the input event).
And *this* is why people use `userEvent` 😉
**Checklist**:

fix(type): ensure the selectionStart/End are consistent with browsers

---

src/__tests__/tab.js
src/index.js

**What**: make tab respect radio groups
**Why**: fixes bugs / inaccurate simulation with `tab()` naively focusing all radio buttons
**How**: ignore radio buttons that aren't checked or at the ends within their named groups
**Checklist**:
The algorithm I used to prune irrelevant radio buttons is a bit ugly and hacky because of all the edge cases, so I'd appreciate any ideas to improve it. We also might need to carefully document this change as it could cause tests to fail if they're relying on the incorrect focusing behavior (though changing incorrect functionality to fix a bug is technically not a breaking change in semver).

fix(tab): make tab respect radio groups (fix #207)

---

README.md
src/__tests__/hover.js
src/__tests__/unhover.js
src/index.js
typings/index.d.ts

**What**: Add `hover()` for hovering elements
**Why**: Testing tooltips and other behavior involving mouse hovering
**How**: Calling various mouse events
**Checklist**:
__Note:__ I intentionally left the test failing because I could use some help figuring out how to fix it. For some reason, `mouseout` is not added to the list of events, despite being called in the function and `onMouseOut` working in a React test.

feat(hover): Add hover API (fixes #254)

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

**What**: Move contributions to dom-testing-library
**Why**: To reduce churn so there's less work for us and pull request authors to do to migrate issues to dom-testing-library
**How**: Updated readme, contributing, issues, and pull requests documentation (no code changes or deprecations)
**Checklist**:

docs: Move contributions to dom-testing-library

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

Reverts testing-library/user-event#345
We should merge this if the decision to not migrate to `dom-testing-library` now is final

Revert "docs: Move contributions to dom-testing-library"

---

README.md
src/__tests__/tab.js
src/tab.js

Resolves https://github.com/testing-library/user-event/issues/365
**What**: Add `document.body` to the cycled elements in tab sequence
**Why**: The browser allows the active element to be `document.body` when the next selected element is outside the page tab sequence. When the active element is the body (e.g. initial state) then the next reasonable selected element is the first element in the page tab sequence. 
**How**: 
- Consolidate logic around getting the next element to focus
- If the current active element is on the edges of the page tab sequence then focus the `document.body` accordingly
**Checklist**:
1. I was assuming that invoking `document.body.focus` would be undesirable -- opting for just `previousElement.blur` as a means of setting active element to the `body`. However, it …

Cycle focus between the body and page tab sequence

---

src/type.js

**What**:
This fixes #369 
**Why**:
Without this change, when a value is changed programatically  as part of a React onChange event, the selectionRange stays at (0, 0) causing the values to be typed in reverse order.
**How**:
Added an else block to the `setSelectionRange` function that is part of `type`. The conditional already existed to check to see if the value changed programatically and my else adds logic to move the selection range to the end of the input to mimic the behavior of the browser.
**Checklist**:
I attempted to replicate my failing react testing here by using the same format function and setting `event.target.value` when the input event fired. However, the test passed without my change. This leads me to believe that it is a symptom of how the value of an input is …

Add else block to setSelectionRange check

---

src/__tests__/type.js
src/type.js

**What**:
It solves #360.
**How**:
In the actual code handling the point, I concatenate the input's previous value.
I tried to keep the changes as little as possible once I'm not used to neither to the events nor to the lib.
**Checklist**:

Fix leading number being trimmed on point type

---

src/__tests__/paste.js
src/__tests__/type.js
src/paste.js
src/type.js
src/utils.js

**What**:
I have thrown a new `TypeError` if the user calls `userEvent.type` or `userEvent.paste` with an element that has no value. 
This PR is part of issue #356.
**Why**:
Because as it was before the PR the error was not very helpful
**How**:
By checking if the currentElement has value property. 
The message thrown is like this `the current element is of type BODY and doesn't have a valid value`
**Checklist**:

fix: add message if type/paste function is called with an invalid element

---

src/tab.js

**What**: Remove `tabIndex` management for `tab` method
**Why**: These pieces of code are not needed anymore with the current version of jsdom. 
**How**: Removed and re-ran test suite. 
**Checklist**:
This is a followup from https://github.com/testing-library/user-event/pull/368

refactor(tab): remove tabIndex set and unset for jsdom

---

src/__tests__/deselect-options.js
src/__tests__/select-options.js
src/select-options.js

fix #358 
**What**:
This PR will fix the issue that events (onChage/input) are not fired on ancestors.
This issue was related to a problem with React because it fires event on bubbling phase. 
As we can see from the images below 
the change event is an `Event` of type `change` 
the input event is an `Event` of type `input`
Both events are of a generic event type. 
**Why**:
Because in particular with React the change event is fired but the onChange listener didn't work
**How**:
By calling 
```
fireEvent(
select,
createEvent('input', select, {
bubbles: true,
cancelable: false,
composed: true,
...init,
}),
)
fireEvent.change(select, init)
```
**Checklist**:

fix: update onChange/input events fired on selected option

---

package.json

**What**:
This PR disables the `testing-library/no-dom-import` eslint rule for the project.
**Why**:
The project currently imports directly from `@testing-library/dom` which causes the linter to throw and fail the pre-commit hook which makes it impossible to commit without bypassing the commit hook. This was @kentcdodds's suggested solution [here](https://github.com/testing-library/user-event/issues/380#issuecomment-649155263).
**How**:
Updated `package.json` to turn this specific rule off.
**Checklist**:

chore: disable testing-library/no-dom-import eslint rule

---

src/__tests__/upload.js
src/upload.js

Fixes #380.
**What**:
This PR fixes a bug in the `.upload()` function that's very similar to #370. The cause of the bug and the fix are basically the same.
**Why**:
In React, starting with user-event v12 the `onChange` and `onInput` callbacks stopped working for `<input type="file" />`.
**How**:
Very similar to #370:
- Input event: passing the `bubbles: true` option to the event's options.
- Change event: Use `fireEvent.change` instead of `fireEvent(input, createEvent('change', ...`.
**Checklist**:
**Notes**:
As I mentioned in the [related issue](#380), we should probably check the rest of the changes in case some other similar functionality broke with the recent changes.

fix: React onChange/onInput events not triggering on input type="file" file upload

---

package.json
src/blur.js
src/clear.js
src/click.js
src/focus.js
src/hover.js
src/paste.js
src/select-options.js
src/tab.js
src/type.js
src/upload.js
src/utils.js

**What**: ensure all events are fired in the eventWrapper
**Why**: Closes #384
**How**: create a helper function to make it easier to wrap all functions in the eventWrapper
**Checklist**:
~- [ ] Documentation~ N/A
~- [ ] Tests~ N/A
~- [ ] Typings~ N/A

fix: ensure all events are fired in the eventWrapper

---

src/type.js

fix(type): correct wrapping

---

src/blur.js
src/clear.js
src/click.js
src/focus.js
src/hover.js
src/paste.js
src/select-options.js
src/tab.js
src/type.js
src/upload.js
src/utils.js

**What**: do not wrap the whole function in the event wrapper
**Why**: Closes #387
**How**: Remove the `wrapInEventWrapper` utility and use a simple event wrapper instead.
**Checklist**:
~- [ ] Documentation N/A~
~- [ ] Tests N/A~
~- [ ] Typings N/A~

fix: do not wrap the whole function in the event wrapper

---

README.md
package.json
src/__tests__/click.js
src/__tests__/deselect-options.js
src/__tests__/paste.js
src/__tests__/type-modifiers.js
src/__tests__/type.js
src/blur.js
src/focus.js
src/type.js
src/utils.js

**What**:
This fixes https://github.com/testing-library/user-event/issues/406
**Why**:
Because clickable inputs and buttons should be handled differently by `type`.
**How**:
- Added clickable input checks in `type` where it was necessary
- Added support for a special character {space}
- Refactored `type.js` to keep it understandable with these additions
**Checklist**:

fix: button trigger space

---

src/__tests__/type-modifiers.js
src/__tests__/type.js
src/paste.js
src/type.js

**What**:
Closes #407 
**Why**:
Because typing on focusable elements should be possible without getting an error.
**How**:
Checked if an element has a value prop before handling input and selection on it.
**Checklist**:

Fix 407 type on no value elements

---

src/__tests__/type.js
src/type.js

**What**: I have fixed a bug with type function
**Why**: As for the [tweet](https://twitter.com/jacobmparis/status/1280875565885554688) when you run `type` function on an `input` inside a `form` it should `submit` the form if it has a listener. 
**How**: If the `currentElement` is an input and if it has a form I have fired a `submit` event on form
**Checklist**:

fix: submit form on ENTER pressed

---

README.md

**What**:
It closes #413 
**Why**:
**How**:
Added a custom example to show how the user can use the `type` method with a selectedRange.
**Checklist**:

docs: add type with selectionRange example

---

src/__tests__/type.js
src/utils.js

**What**:
Ignore the `maxlength` attribute on `input` elements if the provided `type` is not meant to support it.
**Why**:
Closes #418 
**How**:
Before calculating the new value for the control, confirm that the element is an `input` whose type is one that supports the maxlength attribute, or that the element is a `textarea`. Add a test for the `textarea` case and `input[type=number]`, addressing the original bug report.
**Checklist**:

fix(type): ignore maxlength based on input type

---

src/__tests__/helpers/utils.js
src/__tests__/type.js
src/click.js
src/type.js
src/utils.js

**What**: I have added support for content editable
**Why**: Because user can't type into it 
**How**: Triggering the same events as textarea. Div does not have a value but a textContent
I didn't update `getEventSnapshot` because there is not selector for textContent
**Checklist**:

feat: support contenteditable div

---

src/__tests__/type.js
src/type.js

Follow up #397 
**What**: improve what I have done in the previous PR
**Why**: As suggested by @Jessidhia something was wrong with the current implementation.
A form should be submitted pressing enter in an input only when:
1) A `form` is present
2) The form contains only one input or multiple inputs and a submit button (`input[type="submit"]` or `button[type="submit"]`)
**How**: Updating the current implementation in the modifier
**Checklist**:

fix: improve submit form on ENTER pressed 

---

src/utils.js

**What**:
- Fixes `instanceof` expression in `isClickable`
- Changed global `document` references in utils.js file to `element.ownerDocument`
**Why**:
There's a bug where userEvent.type fails due to a reference error.
**How**:
The changes were made as requested in this issue: https://github.com/testing-library/user-event/issues/434 by Kent.
**Checklist**:
All the tests passed locally and the issue I was running into seem to resolve itself when I attempted to yarn link. I'm not a regular contributor and I have absolutely no idea what's going on here for the most part so feel free to ask me to make any necessary changes to the commit, pr, or issue.

fix: isClickable now specifies element.ownerDocument.defaultView as container for HTMLInputElement

---

src/__tests__/tab.js
src/tab.js

fix #441 
replaces #443 
**What**:
`tab()` did not produce the same tab order as the browser does.
**How**:
Reimplemented how the tab sequence is determined.
* Never dismiss activeElement for tab sequence
* Keep DOM order (ignore tabindex) if activeElement has `tabindex="-1"`
* Reimplemented which radio elements to prune from tab order:
* For radio groups keep only the active radio
* If there is no active radio, keep only the checked radio
**Checklist**:

fix(tab): tab order on radio and tabindex=-1

---

src/__tests__/helpers/utils.js
src/__tests__/tab.js

**What**:
The test setup function was written with testing a single element in mind.
Tests working on a sequence of elements needed to either wrap their sequence in an extra `<div>` or access their elements per
```js
const { element} = setup(/*...*/);
element.parentElement.children
```
Both don't improve readability.
The event helpers were set up on the first element.
**How**:
Include an extra property `elements` for the sequence of elements.
If there is more than one element, set up the event helpers on the container.
**Checklist**:
What do you think? Ready or could we do better? Should we refactor more tests first?

refactor: test setup

---

src/__tests__/click.js
src/__tests__/hover.js
src/__tests__/upload.js
src/hover.js

**What**:
pointerEnter/mouseEnter and pointerLeave/mouseLeave don't bubble but are called for every parent (with `e.target` being set to the parent).
https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseenter_event
**Why**:
React normalizes this behaviour but it's not compatible with the native DOM/Preact.
**How**:
For hover/unhover, fire these events for all parent elements as well.
**Checklist**:

Also fire pointer/mouseEnter/-Leave on parents

---

typings/index.d.ts

**What:**
Fix missing `paste` argument in typings. 
**Why:**
Fixes #452
**Checklist**:

Typings: fix paste missing argument

---

src/__tests__/type-modifiers.js
src/__tests__/type.js
src/type.js

**What**:
When using `{enter}`:
- Skips element click when keydown/keypress is prevented
- Skips `'\n'` input when keydown/keypress is prevented 
- Skips form submission when keydown/keypress is prevented 
**Why**:
user-event does not properly emulate browser behavior when using `preventDefault()` with `{enter}`.
Here is a sandbox with a couple tests that should pass but do not: 
https://codesandbox.io/s/user-event-issue-with-enter-and-preventdefault-sr3i7?file=/src/__tests__/App.test.js
**How**:
- Moved event logic inside `keyDownDefaultNotPrevented` and `keyPressDefaultNotPrevented` if statements so it is skipped with `preventDefault()`
- Added tests to confirm this behavior
Not a huge fan of the additional level of nesting in  `handleEnter`, but also didn't think this was a large …

Skip certain events on {enter} when default behavior is prevented

---

src/__tests__/focus.js
src/__tests__/tab.js
src/utils.js

fix #466 
**What**: `tab` attempts to focus hidden type inputs
**Why**: Hidden-type input elements do not receive tab focus in common browsers, but `tab` fails to exclude them from its tab-able element list which produces incorrect behavior.
**How**: Update `FOCUSABLE_SELECTOR` to exclude hidden inputs.
**Checklist**:

fix: exclude hidden type inputs from focusable selector

---

src/__tests__/helpers/utils.js
src/__tests__/select-options.js
src/select-options.js

**What**:
Added a few behaviors when selecting a `listbox` option to `selectOptions` 
**Why**:
After adding the `role="option"` selector it was missing those behaviors to work as expected
**How**:
Added those behaviors listed in [this comment](https://github.com/testing-library/user-event/issues/469#issuecomment-713528494) according to [w3](https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html)
**Checklist**:

Added listbox options support in selectOptions

---

src/__tests__/type.js
src/keys/navigation-key.js
src/type.js

Note: WIP! I am running into a few problems and would like advice.
**What**:
Implements [navigation keys](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values#Navigation_keys) support in `type` method:
- Arrows
- Home and end
- Page up and down
**Why**:
It is reasonable for a user to use keyboard navigation while interacting with an interactive element. An interactive element could be an input (where a user would type into) or an accessible UI with keyboard support (no typing but it handles key events).
**How**:
- Handles new key events while typing: e.g. `Brek{arrowleft}a{arrowright}fast` -> `Breakfast`
- Handles new key events with modifier while typing: e.g. `Breakfast{shift}{arrowleft}{/shift}` -> `Breakfas{selection}t{/selection}`
**Checklist**:
Closes: …

Feature: Implement cursor navigation with navigation keys

---

README.md

**What**:
Documenting the new `{arrowleft}` and `{arrowright}` special characters introduced in #404.
**Why**:
The feature was released in [12.2.0](https://github.com/testing-library/user-event/releases/tag/v12.2.0) but not documented. This PR fixes it.
**How**:
I added the new special characters to the README. Since they're not meta characters, I added them before the list of meta characters instead of at the end of the list, for proper grouping.
**Checklist**:

docs: add {arrowleft} and {arrowright} special characters

---

package.json
typings/index.d.ts
typings/test.ts
typings/tsconfig.json

**What**: The TypeScript type for the `type` function will now only return a `Promise` when given a `delay` option.
**Why**: #480
**How**: Updated type declaration and added basic type tests.
**Checklist**:

fix(type): only return Promise with delay

---

README.md

**What**: Encouraging the use of the `default` export from User Event's CJS build
**Why**: If you don't do this, you'll get errors about properties missing from the top level build (like #485)
**How**: Destructuring (supported since Node 6, and Node 10 is the oldest supported version)
**Checklist**:

Fix documented require usage (fix #485)

---

README.md
src/__tests__/type-modifiers.js
src/type.js

**What**: Adding CapsLock to the modifier key support so that tests using CapsLock can be implemented.
**Why**: When typing and using the CapsLock modifier, we need to be able to write tests that implement the CapsLock key.
**How**: Added a test to the type-modifiers file, then implemented the suggested changes from Kent C Dodds office hours to the type file.
**Checklist**:
- [N/A] Typings

feat: add capslock to userEvent.type

---

README.md
src/__tests__/type.js
src/type.js
src/utils.js

**What**: Adding support for `<input type="time" />`. Check #484 
**Why**: That type of input does not work. It does with `fireEvent`, though
**How**: Adding the functionality for it. I had to interpret the typed characters to hours and minutes, adding the `:` between both.
**Checklist**:

feat(type): add time input support

---

README.md
src/__tests__/type.js
src/type.js

**What**:
These changes add support for the arrow up and down keys to `userEvent.type`.
**Why**:
Arrow up and down keys are used for various accessibility reasons and are part of regular user actions.
**How**:
I added two functions, `handleArrowDown` and `handleArrowUp`, and tied those into the existing special character map.
**Checklist**:
Unless something unexpected comes up, this is probably ready for merging immediately.
Closes #503

Support arrowup and arrowdown events

---

README.md
src/index.js
src/type.js
typings/index.d.ts

**What**: Create and expose `specialChars` map
**Why**:
* It can help to avoid typos providing the constant values;
* Instead of creating the set manually in each project again and again, it could be more convenient to use the official, always up-to-date one.
**How**:
* Create a constant `specialCharMap`
* Link it with `specialCharCallbackMap`
* Export the constant from `src/type.js` and create a named export of the constant called `specialChars` in `src/index.js`
* Add an appropriate enum in `typings/index.d.ts` called `specialChars`
* Add `specialChars` section to `README.md`
**Checklist**:
P.S.: I've defined enum because `const` is not allowed in `index.d.ts`. If `src/type.js` could be written in TypeScript, it could be possible to use a [const …

feat(specialChars): Create and expose `specialChars` map

---

README.md

**What**:
Hi, it's me again! I also noticed that the second example test code in READE.md doesn't work.
```js
✕ double click (24 ms)
● double click
TestingLibraryElementError: Unable to find an element by: [data-testid="checkbox"]
<body>
<div>
<input
id="checkbox"
type="checkbox"
/>
</div>
</body>
8 |   const onChange = jest.fn();
9 |   render(<input type="checkbox" id="checkbox" onChange={onChange} />);
> 10 |   const checkbox = screen.getByTestId("checkbox");
|                           ^
11 |   userEvent.dblClick(checkbox);
12 | 
```
To fix this, we can add a `data-testid` attribute to the input element but I thought it would be better to query by role because it only renders a single checkbox.
**Checklist**:

docs: getByTestId doesn't work

---

README.md

**What**:
Hi, I'm new to this project. While just following the README.md, I noticed that the very first example test code doesn't work.
```js
✕ click (90 ms)
● click
expect(element).toHaveAttribute("checked", true) // element.getAttribute("checked") === true
Expected the element to have attribute:
checked=true
Received:
null
```
I realized that using `toBeChecked()` makes the test pass.
**Why**:
I played around with this checkbox on the dev tools on my browser and I noticed that the `checked` attribute doesn't actually get added to the input element when I clicked the checkbox.
**Checklist**:

docs: toHaveAttribute doesn't work

---

src/__tests__/helpers/utils.js
src/__tests__/select-options.js
src/select-options.js

**What**:
These changes fix bugs on selectOptions.
**Why**:
1. `selectOptions` failed to trigger correct events on options with `role` attribute. - see #542
2. `selectOptions` missed pointer events that happen when selecting an option of regular `<select>`.
3. `selectOptions` made the false assumption the browser would change `aria-selected` attributes when clicking an element with `role="option"`.
See https://codesandbox.io/s/user-event-changle-handler-with-role-forked-d5ubs?file=/src/LoggingSelects.js for tracking events that actually happen in the browser.
**How**:
1. Decide which event pattern to follow based on element type of the `listbox` instead of `role` attribute of the `option`.
2. Add the pointer events observed in the browser.
3. Move event handling into utility component and …

fix: selectOptions

---

src/upload.js

**What**:
```js
const f = new File(/*...*/)
// these two will be equivalent
userEvent.upload(element, [f])
userEvent.upload(element, f)
```
**Why**:
Previous implementation required the user to provide `File` for single file inputs and `File[]` for multiple file inputs.
**How**:
Convert to an array if it is not.
Truncate to length 1 if input is not multiple.
**Checklist**:

fix(upload): accept File or File[] #529

---

src/__tests__/utils.js
src/select-options.js
src/utils.js

Add a helper to verify the element type in different environments.
**What**:
Add a helper to utils.
This can be removed from this library and replaced by a shared helper in `@testing-library/dom` once it is bumped to a version that includes https://github.com/testing-library/dom-testing-library/pull/885.
**Why**:
See #550 
**How**:
The helper tries to find the element constructor on the window.
As the window is neither required to be associated with the observed document nor is it required to provide any element constructors, the helper provides a fallback for other environments than Jest+JSDOM.
**Checklist**:
- N/A Typings

fix: check element type in different environments

---

src/__tests__/type.js
src/type.js
src/utils.js

**What**: in `handleEnter`, there is currently a check for whether the element is clickable, and if it is, it fires a click event on that element. This PR includes anchor tags (with truthy `href` values) in that check.
**Why**: anchor tags are incorrectly missed out of this logic – browsers fire click events on anchor tags when they are focused and the user presses the `Enter` key.
**How**: included anchor tags in the `isClickable` util function.
**Checklist**:

Support 'Enter' key press on links

---

src/__tests__/upload.js
src/upload.js

**What**: Don't allow to upload files with invalid formats.
**Why**: Files with formats that aren't accepted aren't uploaded in an input file, in fact, it's not even allowed to select them, so the tests should also follow the same behavior.
**How**: Verify if the element has an `accept` attribute, if it does, verify if the file/files match the MIME types specified. 
**Checklist**:

fix: do not allow to upload files with invalid formats

---

src/__tests__/click.js
src/click.js

**What**:
Focus closest focusable ancestor of the clicked element.
**Why**:
See #566 
**How**:
Only `blur()` if the clicked element does not have a focusable ancestor.
**Checklist**:
- n/a Documentation
- n/a Typings

fix(click): focus closest focusable (#566)

---

README.md
src/__tests__/upload.js
src/upload.js
typings/index.d.ts

**What**:
Add `applyAccept` option to `userEvent.upload` that defaults to `false`.
**Why**:
Filtering the files for the the input causes problems for those testing their own filters.
https://github.com/testing-library/user-event/pull/558#issuecomment-783397519
Those who want to test their accept attributes can opt-in per:
```js
userEvent.upload(element, files, undefined, { applyAccept: true })
```
**How**:
Add an options parameter to the API.
**Checklist**:

feat(upload): accept filter option

---

typings/index.d.ts

**What**: Added home and end to the specialChars enum in typings
**Why**: In PR #536 home and end typings were not added, so `specialChars.home` could not be used with typescipt
**How**: added the missing typings
**Checklist**:

fix(typings): add home and end to specialChars enum

---

src/__tests__/upload.js
src/upload.js

**What**:
Do not fire an input event if the user selects the same files again.
Do fire an input event if the user selects no files when files have been selected before.
**Why**:
See #574 
**How**:
Compare the `files` provided by the user with `input.files`.
**Checklist**:
- N/A Typings

fix(upload): fire input event when files change (#574)

---

src/__tests__/tab.js
src/__tests__/utils.js
src/tab.js
src/utils.js

**What**:
Exclude descendants of hidden elements.
Replaces #556 
**Why**:
Browser does not include hidden parts of the DOM tree in tab order.
**How**:
Run `window.getComputedStyle()` for every ancestor element.
If one is hidden, exclude the element from tab order.
**Checklist**:
- N/A Typings

fix(tab): exclude hidden descendants

---

src/__tests__/keyboard/getNextKeyDef.ts
src/__tests__/type.js
src/keyboard/getNextKeyDef.ts

**What**:
Fix parsing modifiers as printable characters.
**Why**:
Closes #587 
**Checklist**:
- N/A Typings

fix(keyboard): parse modifiers as characters

---

src/__tests__/click.js
src/click.ts

**What**:
Dispatch `contextmenu` instead of `click` for right button clicks.
**Why**:
Closes #445 
**How**:
Check `button === 2` before calling `fireEvent.click`/`fireEvent.contextmenu`
**Checklist**:
- N/A Typings

fix: right click triggers contextmenu

---

src/__tests__/upload.js
src/upload.ts

**What**:
Implement [`iterable`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterable_protocol) on `target.files`.
**Why**:
MDN states that [`HTMLInputElement.files`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#htmlattrdeffiles) is a [`FileList`](https://developer.mozilla.org/en-US/docs/Web/API/FileList).
The browser also implements the `iterable` on this object, and some libraries rely on it:
Closes #576 
**Checklist**:
- N/A Typings

fix(upload): implement iterable on input.files

---

src/paste.ts

**What**: Fix the event init type of paste by changing from MouseEventInit to ClipboardEventInit. This aligns with the type definition of fireEvent for pasting: https://github.com/testing-library/dom-testing-library/blob/master/src/event-map.js#L11-L14
**Why**: Types should be correct.
**How**: N/A
**Checklist**:

fix(paste): correct the paste event type (#512)

---

src/__tests__/keyboard/plugin/character.ts
src/keyboard/plugins/character.ts
src/utils/edit/getSelectionRange.ts

**What**:
Dispatch `input` event with `inputType: 'insertParagraph'` on `contenteditable` if `shiftKey: false`.
Fix an exception if `getSelectionRange` is called on `contenteditable` and `Selection.rangeCount === 0`
**Why**:
Closes #605 
**Checklist**:
- N/A Typings

fix(keyboard): inputType for Enter on contenteditable

---

src/__tests__/keyboard/keyboardImplementation.ts
src/__tests__/type-modifiers.js
src/keyboard/keyboardImplementation.ts

**What**:
Remove `keypress` and `input` events for character input if `ctrlKey` or `altKey` is `true`.
**Why**:
Closes #613 
**How**:
Don't trigger `keypress` in `keyboardImplementation`.
This also disables the default `keypress` behavior (i.e. `input` for characters).
**Checklist**:

fix(keyboard): omit keypress with ctrlKey or altKey

---

src/utils/edit/calculateNewValue.ts
src/utils/edit/hasUnreliableEmptyValue.ts
src/utils/edit/selectionRange.ts

**What**:
Replace absolute imports with relative imports.
**Why**:
Closes #620 
**Checklist**:

fix: relative imports

---

src/__tests__/clear.js
src/__tests__/keyboard/index.ts
src/__tests__/keyboard/plugin/functional.ts
src/__tests__/type-modifiers.js
src/__tests__/type.js
src/__tests__/utils/edit/calculateNewValue.ts
src/keyboard/plugins/arrow.ts
src/keyboard/shared/fireInputEventIfNeeded.ts
src/utils/edit/selectionRange.ts

**What**:
Apply new value and selection range before `input` event so that `input` handlers can use it.
Get correct selection range for `[ArrowLeft]` and `[ArrowRight]` when active element does not support selectionRange.
**Why**:
Closes #515 
**Checklist**:

fix: apply changes before input event

---

package.json
src/__tests__/react/tsconfig.json
src/__tests__/react/type.tsx
src/keyboard/shared/fireInputEvent.ts
tsconfig.json

**What**:
Change element properties while hiding the change from React.
**Why**:
Closes #624 
**How**:
React keeps track of properties by replacing the PropertyDescriptor.
We replace the PropertyDescriptor with the native one before setting the property and reapply React's PropertyDescriptor afterwards.
This way React should detect the value on the `input` event as a new value and dispatch a `SyntheticEvent` for `onChange`.
**Checklist**:

fix(keyboard): trigger onChange in React

---

src/__tests__/keyboard/plugin/character.ts
src/keyboard/plugins/character.ts

**What**:
Ignore otherwise valid characters that do not trigger `input` events and change the displayed value at that position.
**Why**:
Closes #606 
**How**:
Test the resulting new value against known invalid patterns.
**Checklist**:

fix(keyboard): suppress invalid input on `<input type="number">`

---

src/__tests__/keyboard/getNextKeyDef.ts
src/__tests__/type.js
src/keyboard/getNextKeyDef.ts
src/type/typeImplementation.ts

**What**:
Fix UncaughtPromiseRejectionWarning for synchronous `userEvent.type()` that previously slipped through out catch.
Promise rejections are reported per `console.error`.
Asynchronous calls remain unaffected. Users can and have to handle promise rejections themselves.
Also includes an improved error message for undefined characters and adds test coverage for the error messages.
**Why**:
Close #633 
**How**:
`Return` the internal promise if it is not `await`ed.
**Checklist**:

fix(type): catch internal promise rejections

---

README.md
src/__tests__/click.js
src/__tests__/dblclick.js
src/__tests__/hover.js
src/__tests__/unhover.js
src/click.ts
src/hover.ts

**What**:
As discussed here: https://github.com/testing-library/user-event/issues/639#issuecomment-816924740 , the new behaviour which was recently added to prevent clicks from being emitted when pointer-events are set to `none` had the side-effect of silently no-oping when this was the case, making it:
- non-trivial to figure out why your next assertion failed, given the click 'executed' in the PoV of the test
- hard to work around libraries which set these pointer events while animating
I've added this behaviour to both the click and double-click.
**Why**:
This change follows the paradigm that testing-library provides for selectors, where `getBy` will throw an error if the element doesn't exist. Similarly, trying to click something which is not clickable should also throw an error, as …

fix(click): throw an error when trying to click with pointer-events set to none

---

src/__tests__/keyboard/plugin/functional.ts
src/utils/click/isClickableInput.ts

**What**:
Fixes issues with pressing Space on a focused checkbox/radio input.  Fixes tests for it.
**Checklist**:
Closes #653

Fix to some tests with [Space], Adds checkbox,radio to clickable inputs

---

.all-contributorsrc
README.md
src/__tests__/paste.js
src/__tests__/upload.js
src/paste.ts
src/upload.ts

Fixes #648
**What**: Relaxing element argument types to match the type returned by react-testing-library queries.
**Why**: 
To allow user-event functions to be used with RTS queries without type casting.
**How**:
I'm narrowing the element type by checking that the passed elements are instances of valid element types. Thus, the check is runtime only, which makes sense since DOM queries are not fully type safe.
**Checklist**:

Relaxing element type definitions to HTMLElement

---

src/__tests__/keyboard/index.ts
src/keyboard/getNextKeyDef.ts

**What**:
Closes #633 
**Why**:
People updating userEvent get confused by the error messages about expected key descriptors or unexpected brackets.
**How**:
Add a link to the section of the README explaining how userEvent parses the `text` argument.
**Checklist**:
- [N/A] Tests

fix(keyboard): add link to docs in key descriptor error

---

src/__tests__/upload.js
src/upload.ts

**What**:
Closes #667 
**Why**:
`init` argument was deconstructured incorrectly.
The typing of `init.changeInit` was incorrect.
**Checklist**:

fix(upload): apply changeInit correctly

---

src/__tests__/react/keyboard.tsx
src/keyboard/shared/fireInputEvent.ts

**What**:
Closes #664 
Enforce the correct cursor position after input handling
**Why**:
We trick React into picking up the changes on the `input` event. React moves the cursor to the end of the input.
**How**:
Also set the selection range if the value was not changed by an event handler.
**Checklist**:

fix(keyboard): maintain cursor position on controlled React input

---

src/utils/edit/selectionRange.ts

**What**:
`userEvent.type` with selection range does not work as expected in the browser. Closes #677 
**Why**:
When an input or textarea is clicked, the parent div is selected and the `Selection` range should not be updated at the end of `setSelectionRange`.
**How**:
Skip setting `Selection` range for `<input>` and `<textarea>` in `setSelectionRange` utility. (see [comment](https://github.com/testing-library/user-event/issues/677#issuecomment-836280924) on issue)
**Checklist**:

Fix unexpected behavior with setSelectionRange on inputs in the browser

---

package.json
src/__tests__/clear.js
src/__tests__/helpers/utils.js
src/__tests__/hover.js
src/__tests__/paste.js
src/__tests__/type.js
src/__tests__/upload.js
src/__tests__/utils.js

**What**: Upgrade to Jest 27
**Why**: Ensuring compatibility with breaking changes in Jest 27
**How**: Upgrading packages
**Checklist**:

chore: upgrade to Jest 27

---

src/__tests__/type.js
src/keyboard/plugins/arrow.ts

**What**:
added keydownBehavior for textarea
**Why**:
`{arrowleft}` and `{arrowright}` are not working for textarea elements
**How**:
added `textarea` to `isElementType` params in `keydownBehavior`
**Checklist**:

feat: keydownBehavior for textarea

---

src/keyboard/shared/fireInputEvent.ts

**What**:
Fix istanbul ignore.
**Why**:
Previously the `ignore else` had to be writting before `else if` to ignore the consecutive `else`.
Istanbul now seems to expect it right before the `if`.
**How**:
Committed with `--no-verify` as the pre-commit hook lint-fixed the change :shrug: 
**Checklist**:

test: fix istanbul ignore

---

src/__tests__/keyboard/shared/fireInputEvent.ts
src/keyboard/shared/fireInputEvent.ts

**What**:
Closes #682 
**Why**:
The browser dispatches a `change` event when an element with changed value loses focus.
When we alter the element `value`/`textContent`, we dispatch an `input` event but no native `change` event.
**How**:
When setting the `value`/`textContent` an event handler is added to the capture phase of the `blur` event on the `window`.
If the `value`/`textContent` on our element is different than the initial one, we dispatch a `change` event.
**Checklist**:
**Constraints**:
* We can not determine if an element was changed between gaining focus and our first edit.
We could (also) set the initial value on the `focus` event, but for this we would either:
1) add it on the document as side-effect of the `import` (only works if the `document` is …

fix(keyboard): dispatch change event on blur

---

src/click.ts
src/setup.ts
tests/click/tripleClick.ts
tests/setup.ts

**What**:
Add a `userEvent.tripleClick(element)` API.
**Why**:
Triple clicking into an input is a common user interaction to select the value of an input field.
#763 allowed to simulate this per `pointer` API.
**How**:
`userEvent.tripleClick(element)` is a shortcut for:
```jsx
userEvent.hover(element)
userEvent.pointer({keys: '[MouseLeft][MouseLeft][MouseLeft]', target: element})
```
**Checklist**:

feat: add `userEvent.tripleClick` API

---

src/keyboard/getNextKeyDef.ts
tests/keyboard/getNextKeyDef.ts
tests/type/modifiers.js

BREAKING CHANGE: `{ctrl}`, `{del}`, `{esc}` no longer describe a key. Use `{Control}`, `{Delete}`, `{Escape}` instead.
BREAKING CHANGE: `{alt}`, `{ctrl}`, `{meta}`, `{shift}` no longer imply not releasing the key. Use `{Alt>}`, `{Control>}`, `{Meta>}`, `{Shift>}` instead.
**What**:
Removed implementation for `specialChars` which were removed in #780 
**Why**:
Closes #702 
**Checklist**:

fix!: remove legacy modifier implementations

---

src/paste.ts
src/setup.ts
src/utils/dataTransfer/Blob.ts
src/utils/dataTransfer/Clipboard.ts
src/utils/dataTransfer/DataTransfer.ts
src/utils/dataTransfer/FileList.ts
src/utils/index.ts
tests/paste.js
tests/setup.ts
tests/utils/dataTransfer/Clipboard.ts
tests/utils/dataTransfer/DataTransfer.ts
tsconfig.json

BREAKING CHANGE: The `userEvent.paste` API has new parameters.
**What**:
Replace `userEvent.paste(element, text, init, options)` API with:
```js
userEvent.paste('textToBePasted')
userEvent.paste(clipboardData) // DataTransfer object
userEvent.paste() // Read from Clipboard API
```
**Why**:
Closes #782 
**How**:
Implement logic as outlined in #782
This includes workarounds for the missing APIs in Jsdom.
`userEvent.setup()` replaces `window.navigator.clipboard` as the API is not available outside of secure context.
Uses `DataTransfer` and `ClipboardItem` if available, otherwise(Jsdom) it comes with stubs implementing most features.
A second parameter `options` exist to allow the usage on documents that are not `global.document`.
```
userEvent.paste(data, {document: myDocument}) …
```

feat!: replace `userEvent.paste`

---

src/setup/directApi.ts
src/utility/upload.ts
src/utils/dataTransfer/FileList.ts
src/utils/edit/setFiles.ts
tests/setup.ts
tests/upload.ts
tests/utils/edit/setFiles.ts

BREAKING CHANGE: `init` parameter has been removed from `userEvent.upload`.
**What**:
1. Replace properties on `<input type="file"/>` when changing it per `userEvent.upload`.
2. Remove `init` parameter.
**Why**:
The previous implementation changed the `element.files` properties through `fireEvent` and `event.target.files`.
That assigns the given property to the element.
As a result the element's `value`, `type` and `files` properties don't interact with each other any more like they do in the browser.
The `init` parameter has been removed for `MouseEvent` and there is no good reason to keep it here. See #784 
**How**:
We can not programmatically create a `FileList`.
The browser creates these from trusted events and both the browser and Jsdom prevent constructing it and also prevent …

feat(upload)!: replace element properties

---

src/utils/misc/isVisible.ts
tests/tab.ts
tests/utils/misc/isVisible.ts

**What**:
Calling `userEvent.tab` focuses on element with `visibility: hidden`, which is not expected.
**Why**:
It breaks use cases related to `visibility:hidden` and `userEvent.tab`
**How**:
It is fixed by checking whether the target element has style `visibility: hidden`.
**Checklist**:
This PR is identical to #797 , but targeting `beta`

fix(tab): skip elements with `visibility:hidden`

---

src/utils/misc/hasFormSubmit.ts
tests/keyboard/plugin/functional.ts

**What**:
Given an `HTMLFormElement` that contains both an `HTMLInputElement` and a `HTMLButtonElement`, submit the form when `[Enter]` is pressed on the input element.
**Why**:
Closes #802 
**Checklist**:

fix(keyboard): submit form with `<button/>` on `[Enter]`

---

src/utils/focus/getTabDestination.ts
tests/utils/focus/getTabDestination.ts

**What**:
Change order of tabable elements.
**Why**:
Closes #807 
**Checklist**:

fix(tab): order `tabIndex>0` before `tabIndex=0`

---

src/pointer/pointerPress.ts
src/utils/pointer/firePointerEvents.ts
tests/pointer/click.ts
tests/pointer/drag.ts

**What**:
Remove TODO for #803 as the behavior is inconsistent across browsers.
Trigger `contextmenu` on `mousedown` instead of `mouseup`.
Apply `button` and `buttons` property on all mouse events.
**Checklist**:

fix(pointer): trigger `contextmenu` on `mousedown`

---

src/pointer/pointerPress.ts
tests/pointer/select.ts

**What**:
Do not move focus to `label.control` if a click handler prevents default behavior.
Remove TODO for #805 as the behavior is not consistent across browsers.
**Why**:
Click handler can prevent default behavior for click on label in the browser.
Event handlers on `down`/`up` events seem to have no effect here.
**Checklist**:

fix(pointer): honor click handler on `<label/>`

---

src/utils/keyDef/readNextDescriptor.ts
tests/keyboard/index.ts
tests/keyboard/parseKeyDef.ts

**What**:
Fix key descriptor parsing.
**Why**:
Closes #769 
**How**:
Always treat repeated brackets as escaped brackets.
Support describing keys per printable `key` inside `{` `}` brackets so that they can be used with modifiers.
`{{{ArrowLeft}`:  press+release `{`, then press+release `ArrowLeft`
`{\{>5}`: press `{` for 5 keydowns
**Checklist**:

fix(keyboard): parse escaped bracket followed by descriptor

---

build.js
package.json
tsconfig.build.json

**What**:
Add export as bundled CommonJS.
Fix types export.
**Why**:
Closes #813 
Closes #819 
**How**:
Bundle files in `dist/index.cjs` as CommonJS module.
Bundle files in `dist/index.mjs` as EcmaScript module.
Export types to `dist/types`.
Point `main` to CJS export.
Point `module` to ESM export.
Let `exports` resolve any import per `require` to CJS otherwise ESM.
Point `types` to `dist/types/index.d.ts`.
**Checklist**:

fix: export types and commonjs bundle

---

src/pointer/pointerPress.ts
tests/pointer/index.ts
tests/pointer/select.ts

**What**:
Fire pointer events when clicking disabled input elements.
**Why**:
Closes #804
**Checklist**:

fix(pointer): fire pointer events on disabled elements

---

src/keyboard/plugins/arrow.ts
src/utils/edit/prepareInput.ts
src/utils/focus/cursor.ts
src/utils/index.ts
tests/keyboard/plugin/arrow.ts
tests/keyboard/plugin/functional.ts
tests/utils/focus/cursor.ts

**What**:
Support cursor movement and editing contenteditable from collapsed selection range a.k.a. a simple cursor when the movement/edit is outside of an already focused TextNode.
**Why**:
Closes #806 
**How**:
Calculate the next cursor position as observed in the browser.
Use `Range` API to manipulate the DOM.
**Checklist**:

feat(keyboard): move cursor and delete content in contenteditable

---

README.md

* Update link to the docs so that it points to docs for this version.
* Remove "Edit the docs". Each docs page includes a link to the specific file to edit. The link to the docs repo in this README is just noise.
* Use same capitalization for License as for the other headers.
**Checklist**:

docs: harmonize README

---

src/pointer/pointerPress.ts
src/utility/upload.ts
src/utils/focus/focus.ts
src/utils/misc/findClosest.ts
tests/pointer/select.ts
tests/utility/upload.ts

**What**:
Focus `document.body` on `mousedown` outside of focusable.
**Why**:
Closes #832 
https://github.com/testing-library/user-event/blob/e74defe418a0527e23a7b6eac89f21004cf0a333/src/pointer/pointerPress.ts#L277-L279
When the mousedown happens (or would have happened) outside of a focusable context,
the focus is moved to `document.body`.
**How**:
Blur `activeElement` when `focus` helper is called with an element outside of focusable context.
**Checklist**:

fix(pointer): blur `activeElement` on click outside of focusable

---

src/event/behavior/click.ts
src/event/behavior/index.ts
src/event/behavior/registry.ts
src/event/dispatchEvent.ts
src/event/index.ts
src/pointer/pointerPress.ts
src/utility/upload.ts
src/utils/index.ts
src/utils/misc/cloneEvent.ts
tests/event/dispatchEvent.ts
tests/utility/upload.ts

**What**:
Replace default behavior as part of the central event dispatching.
**Why**:
The order of events for `userEvent.upload` was incorrect.
When clicking the `<input type="file"/>` element in the browser:
1. The element is focused on `mousedown`
2. The file dialog is opened, which results in a `blur` event on the element.
3. The user selects one or more files, which results in an `input` and `change` event.
4. The file dialog is closed, which results in a `focus` event on the element.
Event handlers on the `click` event can prevent opening the file dialog in the browser.
The previous implementation did not honor `Event.defaultPrevented`.
**How**:
Implement default behavior as plugins to the central `dispatchUIEvent` introduced in #838 .
If a default behavior is implemented by this …

fix(upload): fix order of events

---

src/event/behavior/click.ts
tests/pointer/click.ts

**What**:
Consider the ancestor elements when applying `click` behavior.
**Why**:
If a click happens inside a `<button>`, `<input>`, `<label>` or `<textarea>` element, this changes the default behavior.
Extending the code snippet that focused the associated control of a clicked label to also apply the click on the control
resulted in a loop if the control was nested inside that label.
Closes #848 
Closes #849 
**How**:
https://github.com/testing-library/user-event/blob/d3ce5265ec84d5e8e6675d7e2388c8d0343622af/src/event/behavior/click.ts#L6-L8
**Checklist**:

fix(pointer): consider click context

---

src/clipboard/paste.ts
src/event/behavior/index.ts
src/event/behavior/paste.ts
tests/clipboard/paste.ts

**What**:
The paste event now uses the central event dispatching system introduced in #847 to implement the effects of the `paste` event, which ensures the effects are skipped if `event.preventDefault` is called.
**Why**:
This ensures that the effect of the `paste` event is ignored if `event.preventDefault()` is called on the paste event. This matches the behavior of the paste event in the browser, and is necessary to test sites that rely on this behavior. This fixes #861.
**How**:
The behavior of the `paste` event (which is to insert the clipboard content into the current context if it is editable) has been moved from the `paste` module to a separate module in the `behavior` directory. This effect of pasting is now called by the event dispatching system, which also ensures this effect is …

fix(paste): skip input according to `defaultPrevented`

---

src/clipboard/copy.ts
src/clipboard/cut.ts
src/event/behavior/cut.ts
src/event/behavior/index.ts
src/event/behavior/registry.ts
tests/_helpers/listeners.ts
tests/clipboard/copy.ts
tests/clipboard/cut.ts
tests/event/behavior/keypress.ts

**What**:
Prevent default behavior per `event.preventDefault()`:
* writing to Clipboard on `copy` and `cut` events
* DOM manipulation on `cut`
**Why**:
The issue described in #861 also applies to `cut` and `copy` events.
**How**:
Implement default input behavior for `cut` in event behavior system.
Keep implementation for writing to clipboard in the API (for now), because the event behavior (currently) only supports synchronous operations and writing to Clipboard is always asynchronous.
**Checklist**:

fix(clipboard): prevent default behavior on `copy`/`cut`

---

src/utils/misc/isDisabled.ts
tests/utils/misc/isDisabled.ts

**What**:
Check if an element is disabled according to specs.
**Why**:
Closes #844 
**How**:
Traverse the element and ancestors and check if any of them cause the element being disabled.
`:disabled` pseudo-class should yield the correct value but doesn't in JSDOM.
**Checklist**:

fix: check for inherited `:disabled`

---

src/utils/edit/input.ts

chore: fix typo in input.ts

---

src/keyboard/parseKeyDef.ts
src/pointer/parseKeyDef.ts
src/utils/keyDef/readNextDescriptor.ts
tests/keyboard/parseKeyDef.ts
tests/utils/keyDef/readNextDescriptor.ts

**What**:
Log correct docs link for invalid key descriptors.
**Why**:
Closes #876 
**How**:
Pass down the context in which the `readNextDescriptor` utility is called.
Link to the updated docs.
**Checklist**:

fix: log correct docs link for invalid key descriptors

---

.codesandbox/ci.json
.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

**What**:
Add a Codesandbox template for tests without a JS framework.
**Why**:
Behavior that isn't framework-specific should be reproduced on the native DOM elements and event handlers.
**Checklist**:

chore: add codesandbox template without framework

---

src/document/selection.ts
tests/document/index.ts

**What**:
Support setting the UI selection per `HTMLInputElement.select()`.
**Why**:
Closes #897 
**How**:
Add an interceptor on the method and change `UISelection` accordingly.
**Checklist**:

fix: track calls to `HTMLInputElement.select()`

---

.eslintrc.js
eslint/explicit-globals.js
package.json

**What**:
Add a lint rule against implicit use of global variables.
**Why**:
This enforces to get things like `document` or `window` explicitly from `globalThis` or from local scope.
**How**:
Add a local lint rule per `--rulesdir=eslint`.
**Checklist**:

chore: add lint rule against implicit globals

---

src/options.ts

**What**:
This PR fixes a regression introduced [here](https://github.com/testing-library/user-event/pull/790/files#diff-2123f97b7bf9480a61717c843425e483e8d97819592e8c04e4e149eb65b451e8R116)
**Why**:
At Storybook we have a package [@storybook/testing-library](https://github.com/storybookjs/testing-library) which we use user-event and we'd love to upgrade to v14, but until browser support is sorted we have to hold off.
**How**:
This PR changes a reference from `global` to `globalThis` to enable browser support. 
**Checklist**:

fix: use globalThis instead of global for browser support

---

src/setup/setup.ts
src/utils/dataTransfer/Clipboard.ts
src/utils/edit/buildTimeValue.ts
src/utils/misc/wait.ts

**What**:
Remove global references or make them explicit.
**Why**:
There might be problems with shadowed global variables in testing environments. See #892 
The way e.g. jest hoists code we cannot be sure that a reference to e.g. `window` in a module is a reference to `globalThis.window`. We further cannot be sure that e.g. `document.defaultView` references the same object as `window`.
Although this is probably no issue in most cases we should be explicit about where we access objects through variables the user provided per `setup()` and where we access through global variables.
#929 , #931 enforce to be explicit about access to globals. Any reference that can't be found per text search for `globalThis.` results in a linting error.
**How**:
- Remove global references from `Clipboard` …

fix: remove implicit global references

---

tests/utils/misc/wait.ts

**What**:
Rewrite test.
**Why**:
Previous test would not fail if `advanceTimers` wasn't applied.
https://github.com/testing-library/user-event/blob/ee062e762f9ac185d982dbf990387e97e05b3c9d/tests/utils/misc/wait.ts#L3-L9
`validate` script doesn't typecheck tests :disappointed: 
We need to fix that.
**Checklist**:

test: correct false-negative for advancing timers

---

src/utils/focus/selection.ts
tests/utils/focus/selection.ts

**What**:
Do nothing when trying to move cursor without a selection range.
**Why**:
Closes #901 
**How**:
Check for `selection?.focusNode`.
**Checklist**:
**Additional information**
https://codesandbox.io/s/jovial-turing-q3mm8u?file=/src/App.test.js

fix: guard against selection without range

---

src/setup/setup.ts
tests/keyboard/index.ts
tests/keyboard/keyboardAction.ts
tests/pointer/index.ts
tests/setup/_mockApis.ts
tests/setup/index.ts

**What**:
Wait for asynchronous state updates before leaving the `asyncWrapper`
**Why**:
Closes #938 
**How**:
Add a `wait` call after the respective method when wrapping in `asyncWrapper`.
That should prevent `act` warnings on the `await` right before an API call as it returns on a fresh macrotask.
**Checklist**:
** Additional information **
Codesandbox example:
https://codesandbox.io/s/billowing-hooks-h5oj5w?file=/src/App.test.js

fix: wait after each method before leaving `asyncWrapper`

---

src/utility/selectOptions.ts
tests/react/_env/setup-env.js
tests/react/index.tsx

**What**:
Wait`delay` after each change per `.selectOptions()`.
For delayed state updates users can utilize the `delay` option.
**Why**:
Closes #935 
**How**:
Add a `wait()` call after each click.
This doesn't resolve all the shortcomings of that API.
`pointer()` should be extended regarding special behavior inside native `<select>` and then `.selectOptions()` should just use `.pointer()` internally.
But for now this resolves the issue.
**Checklist**:

fix(selectOptions): wait after each click

---

src/document/selection.ts
src/utils/dataTransfer/Clipboard.ts
src/utils/misc/level.ts

**What**:
Typescript 4.7 infers some types correctly which removed the need for type assertions.
It also throws an error for uninitialized properties on a class. Now the property is assigned after constructing the object.
**Why**:
Upgraded dependencies including `typescript@4.7`
**Checklist**:

refactor: adjust to TS4.7

---

src/document/index.ts
src/document/selection.ts
src/document/setRangeText.ts
src/document/value.ts
tests/document/index.ts

**What**:
Reset UI value and selection on `setRangeText`.
**Why**:
Closes #981
**How**:
Add interceptor.
**Checklist**:

fix(document): track `HTMLInputElement.setRangeText()`

---

src/document/interceptor.ts
src/document/selection.ts
tests/document/index.ts

**What**:
We circumvent the setters/methods on element objects when we change "UI" selection/value.
Do not directly apply prototype setters/methods for programmatic calls.
**Why**:
Closes #986
**How**:
Set default for `applyNative` to `false`.
**Checklist**:

fix(document): use setters/methods on element as default

---

eslint-local-rules/explicit-globals.js
src/utility/upload.ts
src/utils/dataTransfer/DataTransfer.ts
src/utils/dataTransfer/FileList.ts
tests/utils/dataTransfer/FileList.ts
tests/utils/edit/setFiles.ts

**What**:
Flag more implicit globals when linting.
Replace implicit global `FileList` with `window.FileList`.
**Why**:
See #932
**How**:
Don't allow `ImplicitLibVariable`.
Whitelist standard built-in objects.
Ignore types.
**Checklist**:

remove remaining implicit global

---

src/document/index.ts
src/document/selection.ts
src/document/value.ts
src/utils/edit/input.ts
tests/react/index.tsx

**What**:
Apply workaround only if the element is controlled by React17.
Do not reapply cursor position if selection has been changed by user code.
**Why**:
Closes #971 
The rollback to previous value before applying a state update in test environment is specific to React@17.
**How**:
Check if `window.REACT_VERSION === 17` and if the `__react` properties exist on the element, before applying the workaround.
**Checklist**:

fix(document): reduce impact of React@17 workaround

---

src/event/behavior/keydown.ts
src/utils/edit/walkRadio.ts
src/utils/index.ts
tests/event/behavior/keydown.ts

**What**:
Check next/previous radio button in group per arrow keys.
**Why**:
Closes #843 
**How**:
Add default behavior for `keydown`.
**Checklist**:

feat(keyboard): change radio group per arrow keys

---

.github/workflows/ci.yml
.github/workflows/validate.yml
package.json

**What**:
Run `typecheck` during pre-commit.
Run `lint` `test` and `build` in CI.
**Why**:
`build` writes to the file system including `package.json` which might result in uncommitted changes.
The properties set on `package.json` by the build script should not be included in the repository as this might give the false impression that changes there might have an effect on the distributed package.
**How**:
During `pre-commit` hook the `validate` script skips `lint` and `test` and only runs `build` and `typecheck`.
We only need `typecheck` here.
In CI the `validate` script runs `lint`, `test`, `build` and `typecheck`.
The build already includes the typecheck.
=> The `validate` script invoked by the `pre-commit` script directly calls `kcd-scripts typecheck`.
=> The CI explicitly lists `lint`, …

chore: do not build in pre-commit

---

tests/utils/misc/wait.ts

**What**:
Prevent false-positive test due to slow test environment.
**Why**:
Sometimes the execution is delayed just enough to make this assertion fail.
**Checklist**:

test: prevent false-positive with fake timers

---

src/event/createEvent.ts
src/event/dom-events.d.ts
src/event/eventMap.ts
src/event/index.ts
src/event/types.ts
tests/_helpers/listeners.ts
tests/keyboard/modifiers.ts

**What**:
Assign the specific event properties and methods on the events instead of relying on the event constructors.
**Why**:
Some DOM implementations are incomplete. E.g. Jsdom lacks support for `PointerEvent` and it won't be implemented any time soon.
While initializing the events should be out of scope, events lacking the properties we correctly provide for `init` makes for a bad user experience and simply assigning the properties seems sufficient.
Closes #926 
Return correct modifier state for `Alt`, `Control`, `Meta` and `Shift` per `getModifierState`.
**How**:
Replace the `createEvent` imported from `@testing-library/dom` with own implementation.
**Checklist**:

fix(event): be robust against incomplete event implementations

---

package.json

**What**:
Transpile to 2019 syntax.
**Why**:
Closes #1015 
**How**:
Set `jsc.target` per CLI option
Use `es2019` as target for `node12`. https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping
**Checklist**:

fix(build): transpile to es2019 syntax

---

package.json

**What**:
Add `exports` field
**Why**:
Missing `exports` field breaks native ESM import.
See https://github.com/testing-library/user-event/discussions/1021
**How**:
Updated script to always generate `exports` field when creating a dual-build.
**Checklist**:

fix(build): add `exports` field

---

.all-contributorsrc
CONTRIBUTORS.md

See https://github.com/testing-library/user-event/discussions/1021
Bot doesn't recognize comments in discussions

docs: add HillLiu as a contributor for bug

---

.github/workflows/ci.yml

**What**:
Run all steps on the node version provided by `ubuntu-latest` as default.
**Why**:
See #1019 
**Checklist**:

chore: remove unnecessary CI steps

---

package.json

**What**:
`exports[path].types` is added to `package.json` by the build script in the latest version.
The change to the package.json isn't necessary, but let's add it to the changelog this way.
**Why**:
Closes #1024 
See https://github.com/testing-library/user-event/discussions/978
**Checklist**:

fix(build): add `types` field in `exports`

---

testenv/modules/inlineSnapshot.js
testenv/node.js
tests/clipboard/copy.ts
tests/clipboard/cut.ts
tests/clipboard/paste.ts

**What**:
1. Print diff of failing inline snapshots.
2. Use own snapshot matchers in `node` environment.
**Why**:
1. Easier to read than full print of `expected` vs `received`.
2. `jest-snapshot` calls `context.dontThrow()` so that tests pass with failing snapshots. I couldn't find documentation how this is supposed to be configured correctly. So for now we don't use `jest-snapshot` in the toolbox tests.
**Checklist**:

chore: fix snapshot testing

---

src/_interop/dtl.ts
src/_interop/dtlEventMap.ts
src/_interop/dtlHelpers.ts

**What**:
Fixes: #1160 
**Why**:
`@testing-library/dom` doesn’t have a default export.
When trying to import and resolve a default export from `@testing-library/dom` the package would fail.
**How**:
Removing the default export
**Checklist**:

Fix incorrect default import from @testing-library/dom

---

scripts/test.js
src/event/focus.ts
src/event/selection/updateSelectionOnFocus.ts
src/system/keyboard.ts
src/system/pointer/index.ts
src/utils/dataTransfer/DataTransfer.ts
testenv/libs/dom10/index.js
testenv/libs/dom10/package.json
testenv/libs/react18/package.json
testenv/modules/console.js
tests/_helpers/index.ts
tests/_helpers/listeners.ts
tests/clipboard/copy.ts
tests/clipboard/cut.ts
tests/environment/computedStyle.ts
tests/environment/select.ts
tests/event/input.ts
tests/event/selection/index.ts
tests/keyboard/index.ts
tests/keyboard/keyboardAction.ts
tests/pointer/index.ts
tests/utility/clear.ts
tests/utility/type.ts
tests/utils/dataTransfer/DataTransfer.ts
tests/utils/edit/setFiles.ts
tests/utils/pointer/cssPointerEvents.ts

**What**:
Identify the differences between Chrome and Jsdom environment.
**Why**:
Determine if failing tests in Chrome are the result of wrong assumptions in our tests or wrong implementations in our source.
**Checklist**:
**Findings**:
Some of our tests rely on Jsdom-specific behavior and in at least one case the browser implementation has changed.
I've added TODOs (either in test or source) where i could identify the cause of different results in the test environments.
Any new discoveries of differences between Jsdom and Chrome should be added to `tests/environment` so that we can easily keep track of the quirks.
* #553
`prepareElement` is triggered by `focus`. Therefore we fail to track any UI value/selection in browsers.
https://github.com/testing-library/user-event/blob/57c9b655ca2e99 …

test: identify browser/jsdom differences

---

src/utils/dataTransfer/Clipboard.ts
src/utils/dataTransfer/DataTransfer.ts
tests/utils/dataTransfer/DataTransfer.ts

**Why**:
Callback for `DataTransferItem.getAsString()` gets called on new event loop step in browser.
**Checklist**:

fix(clipboard): await `DataTransferItem.getAsString()` callback

---

src/event/createEvent.ts
tests/pointer/move.ts

**What**:
Assign missing pointer coords.
**Why**:
Closes #1037 
**Checklist**:

fix(event): assign pointer coords to MouseEvent

---

src/system/pointer/shared.ts
tests/pointer/move.ts

Fixes #1047
**What**:
Correct coord property "x" to "y" in isDifferentPointerPosition.
**Why**:
It had a typo.
**How**:
N/A
**Checklist**:

Correct coord property "x" to "y" in isDifferentPointerPosition

---

src/system/pointer/shared.ts
tests/pointer/drag.ts

**What**:
Fixing a bug I observed where I tried to simulate click-and-drag, and the second event didn't fire because the logic thought the two positions were equal.
**Why**:
Fixes #1139.
**How**:
Checked https://github.com/bawjensen/user-event/blob/d0362796a33c2d39713998f82ae309020c37b385/src/event/types.ts#L27-L38, and used all those fields in comparison rather than simply `x` and `y`.
**Checklist**:

fix(pointer): make sure to check all fields of `coords` in `isDifferentPointerPosition()`

---

src/event/behavior/keydown.ts
src/event/radio.ts
tests/event/behavior/keydown.ts

**What**:
This PR fixes a bug where keyboard navigation through radio inputs did not work as expected (#1048).
**Why**:
This gives us true-to-life outputs when radio inputs are tested with the keyboard.
**How**:
1. *Sending correct directions for up/down arrows* - Based on native browser interactions [plus this W3C spec for a widget based on radio inputs](https://www.w3.org/WAI/ARIA/apg/example-index/radio/radio-rating.html#kbd_label), Down/Right arrows should move us forward in the group, and Up/Left should move us back. I adjusted `keydown.ts` to send the correct directions for Down and Up key events.
2. *Only advancing one element at a time* - The initial behavior seemed to move us through every valid radio input within a group. I've updated `radio.ts` so that we only move forwards or …

Radio inputs - fix arrow button functionality

---

src/utility/upload.ts
tests/_helpers/listeners.ts
tests/utility/upload.ts

**What**:
Fixes a bug where file upload `input[accept]` is not respected when there are spaces in the `accept` attribute. Closes #1060.
Also raises an error in case the explicitly provided list of files did not have any match. 
**Why**:
HTML attributes are notoriously lenient---if something is valid in HTML, then it should be valid in test cases. The `accept` attribute ignores both letter cases and whitespaces (including new lines). Plus it is very common for users to provide at least 1 space separator for for multi types, e.g. `<input type="file" accept="image/png, image/jpeg" />`.
Raising an error in case of empty filtered file list is more user-friendly than silently fail as a user's test case may fail anyway if an explicit call of `upload` was not successful.
**How**:
The PR handles …

fix(upload): accept type should be more lenient

---

src/keyboard/keyMap.ts

**What**:
add ContextMenu key to default keyboard layout 
**Why**:
The menu key is part of the standard 104 key layout.
**How**:
Researched to ensure the key was standard. Looked up key code on MDN.
**Checklist**:
- [N/A] Tests

keyMap: add ContextMenu key

---

src/system/pointer/index.ts
src/system/pointer/mouse.ts
src/system/pointer/pointer.ts
tests/convenience/click.ts
tests/pointer/click.ts

**What**:
Closes https://github.com/testing-library/user-event/issues/1119
This ensures that click and double click are still fired even when preventDefault is used on pointerdown to prevent mouse compatibility events.
**Why**:
The browsers all work this way, as seen here https://codesandbox.io/s/aged-voice-xjf3dw
**How**:
Click is currently handled in the pointer/mouse class. This is fine, however there is some tracking there which tells us if we can fire the click/double click. As a result I pushed the check for isPrevented down into the mouse actions and only prevented the firing of the relevant events, not everything like it was before.
**Checklist**:

Fix click with pointer compatibility

---

CONTRIBUTING.md
src/event/behavior/click.ts
tests/pointer/click.ts

**What**:
Resolves #1057. This change stops click events from being forwarded to non-focusable inputs from labels.
**Why**:
Currently, click events are being forwarded to inputs from labels. This is expected behavior unless the input is disabled or hidden or otherwise not focusable. This behavior break tests that rely on clicking labels of disabled inputs.
**How**:
The function call forwarding the click was moved inside the conditional checking if the control was focusable.
**Checklist**:
Also, updating the "How to Contribute" egghead tutorial link in CONTRIBUTING.md.
Based on @nknapp's [suggestion](https://github.com/testing-library/user-event/issues/1057#issuecomment-1505985844).

fix: prevent click event on non-focusable control

---

src/options.ts
tests/keyboard/index.ts

#1174
**What**:
This fixes a documentation error and adds a test to verify delay's behavior.
#1174
**Why**:
Correct documentation and quality tests make the library easier to use and adopt. The delay option is an important tool for helping write stable tests against asynchronous code.
**How**:
Comment adjustment. Straight forward test case proving the delay works as described.
**Checklist**:
Thanks for taking the time to review the change. Any feedback is appreciated.

Update delay document and add test confirming the delay behavior

---

src/event/createEvent.ts

**What**:
This PR updates `PointerEvent` to have default width / height set to `1` as per the spec.
* https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/width
* https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/height
**Why**:
`new PointerEvent('xxx')` on most browser implementations should set them `1` by default.
Also some libraries check if a pointer event is _virtual_ or not by looking at the geometry values, while we expect this library to work exactly as the actual interactions.
* ex: [Floating UI](https://github.com/floating-ui/floating-ui/blob/3656e71dbd59078debc393696a50b4b5aee57f65/packages/react/src/utils.ts#L90)
**How**:
Just use `1` as default values on them.
**Checklist**:
- Not needed?

Update PointerEvent to have default width / height set to 1

---

src/keyboard/keyMap.ts
tests/keyboard/parseKeyDef.ts

**What**:
Adding support for brackets to address #1225
**Why**:
To allow easier testing of functionality that relies on both `key` and `code` being valid for keyboard events involving left/right brackets
**How**:
Updated `keyMap.ts`, ran the test suite.
**Checklist**:
I'm unclear whether any documentation needs updating, since I imagine this just falls under the heading of the TODO at the bottom of `keyMap.ts`, i.e. this is simply filling out the mappings.
Also I considered the updates to the existing tests enough, but it's possibly I ought to add more test cases (namely for the right bracket cases).

Add brackets (`[]{}`) to defaultKeyMap for keyboard()/type()

---

.github/PULL_REQUEST_TEMPLATE.md
src/event/behavior/click.ts
tests/pointer/click.ts

**What**:
closes #1237 
**Why**:
Re-dispatching a click event on the control of a label is already skipped for labeled controls that are builtin. This change also skips form associated custom elements (FACEs) since they are always classified as labelable elements and are thus handled by the user agent already.
**How**:
Check whether the `formAssociated` static property exists by reading it from the targets constructor.
**Checklist**:

fix(click): skip explicit re-dispatch for face
