testing-library/user-event

README.md
=> docs: ✏️ add documentation

.all-contributorsrc, README.md
@weyert let me know if you would like to have this one merged
=> Add @weyert as a contributor

.all-contributorsrc, README.md, __tests__/click.js, src/index.js
Basically, a copy of #96 that for some reason wasn't running the tests.
Plus adding @twhitbeck as a contributor
=> Disabled checkbox

package.json, typings/index.d.ts
Added TypeScript definitions for `@testing-library/user-event`-package
=> chore: added TypeScript type definitions

__tests__/react/tab.js, src/index.js
implements https://github.com/testing-library/user-event/issues/167
=> feat: userEvent.tab

__tests__/react/click.js, __tests__/react/dblclick.js, __tests__/vue/click.js, __tests__/vue/dblclick.js, src/index.js
=> fix: add focus event for checkbox/radio

README.md
A small recommendation to make the docs even more clear.
Thanks for making this library :smiley:
=> docs: ✏️ improve clarity of example for selectOptions

package-lock.json, package.json, src/__tests__/wrapping-in-act-is-unnecessary.js
**What**: fix: update DOM Testing Library for some bug fixes
**Why**:
Closes: https://github.com/testing-library/user-event/issues/188
Closes: https://github.com/testing-library/user-event/issues/255
Enables this to be fixed: https://github.com/testing-library/user-event/issues/277
**How**: Update deps to get https://github.com/testing-library/dom-testing-library/pull/600
**Checklist**:
=> fix: update DOM Testing Library for some bug fixes

package.json
=> Bump the peer dep on dom

README.md
=> fix: typo in multiple files upload

src/__tests__/type.js, src/type.js, src/utils.js
**What**:
It closes #399.
**Why**:
**How**:
**Checklist**:
=> fix: type into date input

.github/ISSUE_TEMPLATE.md
**What**:
This is just an addition to the issue template for those, such as myself, whose issues may be fixed by upgrading their version of user-event.
**Why**:
To help people resolve their issues or at least verify their issue hasn't already been fixed in the most recent version of user-event. I discussed this change with @nickmccurdy and he thought it might be a good idea too.
**How**:
Added a comment to ISSUE_TEMPLATE.md right below where the user provides their current version.
**Checklist**:
Happy to make changes to the wording on this. I did a little digging to see if I could programmatically grab the current release version but I think it would probably end up adding more complexity than it's worth because we'd also need a build system to generate this file.
=> Ft issue template update

src/select-options.js
**What**:
This pr aims closing #469 
**Why**:
To also work with [custom selects](https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html)
**How**:
Added an option role attribute into `allOptions` selector
**Checklist**:
=> Added option role into allOptions selector

README.md
**What**:
**Why**: See (this issue)[https://github.com/testing-library/user-event/issues/497
**How**: Updated README at the top-level because I suspect that applies to all of the methods not just click.
**Checklist**:
Feel free to clean up or clarify this language.
=> Doc need for `await` in before/after blocks to avoid warnings

.github/workflows/validate.yml
follow-up #513 
**What**: skip the installation of husky in CI
**Why**: because of an issue with node 15 https://github.com/npm/cli/issues/2033. In any case husky is not really helpful in CI
**How**:
**Checklist**:
=> ci: skip husky install

README.md
=> Add missing quote in README code example

.codesandbox/ci.json
**What**:
Add codesandbox comments to PRs
=> ci: add codesandbox config

.github/workflows/validate.yml
**What**: Don't test with node 10 or 15
**Why**: Node 10 and 15 reached EOL so let's free up some CI resources.
**How**: Remove 10 and 15 from node test matrix.
**Checklist**:
- ~[ ]~ Documentation added to the
[docs site](https://github.com/testing-library/testing-library-docs)
- ~[ ]~ Typescript definitions updated
=> chore: Don't test with node 10 or 15

README.md
**What**:
Update readme with [changes in docs](https://github.com/testing-library/testing-library-docs/commits/main/docs/ecosystem-user-event.mdx)
**Why**:
Most of the readme has been copied to the docs, but several changes in the docs haven't been copied back here yet
This is the first step of my work to move User Event documentation: https://github.com/testing-library/testing-library-docs/issues/519#issuecomment-882126733
**How**:
Reviewed  [all commits to docs](https://github.com/testing-library/testing-library-docs/commits/main/docs/ecosystem-user-event.mdx) (note that the file has been renamed from `.md` to `.mdx`) and copied them here
**Checklist**:
=> docs: update readme with changes in docs

README.md
=> docs: fix Discord links

.github/workflows/validate.yml, jest.config.js, package.json, tests/react/17.tsx, tests/react/_env/react17.js, tests/react/_env/setup-env.js, tests/react/index.tsx
**What**:
Update to React18 to ensure compatibility
**Checklist**:
=> chore: update test environment to React18

src/utils/dataTransfer/FileList.ts, src/utils/edit/setFiles.ts
**What**:
Guard against missing `window.FileList` and invalid `HTMLInputElement.files`.
**Why**:
Closes #940 
**Checklist**:
=> fix(upload): be robust against missing `FileList` implementation

src/index.ts
Fixes https://github.com/testing-library/user-event/issues/1111 and https://github.com/testing-library/user-event/issues/1085
=> Add additional type exports

src/document/patchFocus.ts, src/keyboard/parseKeyDef.ts, src/utils/focus/cursor.ts
blured -> blurred
defintions -> definitions
foward -> forward
Correct the spelling of some typos. 
To improve code readability.
=> chore: Fix some typos in code
